# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-python-release

on:
  release:
    types:
      - created

jobs:

  publish-pypi:
    name: release-publish-pypi
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: build package distributable
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: true
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine wheel
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload dist/*
